// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The NewTerminalState. </summary>
    public partial class NewTerminalState
    {
        /// <summary> Initializes a new instance of NewTerminalState. </summary>
        /// <param name="status"></param>
        public NewTerminalState(TerminalStatus status)
        {
            Status = status;
            AdditionalProperties = new ChangeTrackingDictionary<string, object>();
        }

        /// <summary> Gets the status. </summary>
        public TerminalStatus Status { get; }
        /// <summary> Additional Properties. </summary>
        public IDictionary<string, object> AdditionalProperties { get; }
    }
}
