// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The NewTerminalRole. </summary>
    public partial class NewTerminalRole
    {
        /// <summary> Initializes a new instance of NewTerminalRole. </summary>
        /// <param name="role"></param>
        public NewTerminalRole(TerminalRoles role)
        {
            Role = role;
        }

        /// <summary> Gets the role. </summary>
        public TerminalRoles Role { get; }
    }
}
