// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    public partial class NewTerminalAssignmentRequest : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Role))
            {
                writer.WritePropertyName("role");
                writer.WriteStringValue(Role.Value.ToString());
            }
            if (Optional.IsDefined(Type))
            {
                if (Type != null)
                {
                    writer.WritePropertyName("type");
                    writer.WriteStringValue(Type);
                }
                else
                {
                    writer.WriteNull("type");
                }
            }
            if (Optional.IsDefined(Address))
            {
                if (Address != null)
                {
                    writer.WritePropertyName("address");
                    writer.WriteStringValue(Address);
                }
                else
                {
                    writer.WriteNull("address");
                }
            }
            if (Optional.IsDefined(TerminalId))
            {
                if (TerminalId != null)
                {
                    writer.WritePropertyName("terminalId");
                    writer.WriteStringValue(TerminalId);
                }
                else
                {
                    writer.WriteNull("terminalId");
                }
            }
            writer.WriteEndObject();
        }
    }
}
