// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    public partial class PageQuery
    {
        internal static PageQuery DeserializePageQuery(JsonElement element)
        {
            Optional<int> page = default;
            Optional<int> size = default;
            Optional<IReadOnlyList<string>> sortBy = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("page"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    page = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("size"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    size = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("sortBy"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        sortBy = null;
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    sortBy = array;
                    continue;
                }
            }
            return new PageQuery(Optional.ToNullable(page), Optional.ToNullable(size), Optional.ToList(sortBy));
        }
    }
}
