// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The PageQueryResultOfTerminalAssignmentRequest. </summary>
    public partial class PageQueryResultOfTerminalAssignmentRequest
    {
        /// <summary> Initializes a new instance of PageQueryResultOfTerminalAssignmentRequest. </summary>
        /// <param name="totalItems"></param>
        /// <param name="totalPages"></param>
        /// <param name="query"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="query"/> is null. </exception>
        internal PageQueryResultOfTerminalAssignmentRequest(int totalItems, int totalPages, PageQuery query)
        {
            Argument.AssertNotNull(query, nameof(query));

            TotalItems = totalItems;
            Items = new ChangeTrackingList<TerminalAssignmentRequest>();
            TotalPages = totalPages;
            Query = query;
        }

        /// <summary> Initializes a new instance of PageQueryResultOfTerminalAssignmentRequest. </summary>
        /// <param name="totalItems"></param>
        /// <param name="items"></param>
        /// <param name="totalPages"></param>
        /// <param name="query"></param>
        /// <param name="self"></param>
        /// <param name="first"></param>
        /// <param name="next"></param>
        /// <param name="previous"></param>
        /// <param name="last"></param>
        internal PageQueryResultOfTerminalAssignmentRequest(int totalItems, IReadOnlyList<TerminalAssignmentRequest> items, int totalPages, PageQuery query, Uri self, Uri first, Uri next, Uri previous, Uri last)
        {
            TotalItems = totalItems;
            Items = items;
            TotalPages = totalPages;
            Query = query;
            Self = self;
            First = first;
            Next = next;
            Previous = previous;
            Last = last;
        }

        /// <summary> Gets the total items. </summary>
        public int TotalItems { get; }
        /// <summary> Gets the items. </summary>
        public IReadOnlyList<TerminalAssignmentRequest> Items { get; }
        /// <summary> Gets the total pages. </summary>
        public int TotalPages { get; }
        /// <summary> Gets the query. </summary>
        public PageQuery Query { get; }
        /// <summary> Gets the self. </summary>
        public Uri Self { get; }
        /// <summary> Gets the first. </summary>
        public Uri First { get; }
        /// <summary> Gets the next. </summary>
        public Uri Next { get; }
        /// <summary> Gets the previous. </summary>
        public Uri Previous { get; }
        /// <summary> Gets the last. </summary>
        public Uri Last { get; }
    }
}
