// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The TerminalLookup. </summary>
    public partial class TerminalLookup
    {
        /// <summary> Initializes a new instance of TerminalLookup. </summary>
        /// <param name="type"></param>
        /// <param name="address"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="address"/> is null. </exception>
        public TerminalLookup(ServerTerminalType type, string address)
        {
            Argument.AssertNotNull(address, nameof(address));

            Type = type;
            Address = address;
        }

        /// <summary> Gets the type. </summary>
        public ServerTerminalType Type { get; }
        /// <summary> Gets the address. </summary>
        public string Address { get; }
    }
}
