// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    public partial class TerminalAssignment
    {
        internal static TerminalAssignment DeserializeTerminalAssignment(JsonElement element)
        {
            string tenantId = default;
            DateTimeOffset timeStamp = default;
            Optional<string> terminalId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("tenantId"))
                {
                    tenantId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("timeStamp"))
                {
                    timeStamp = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("terminalId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        terminalId = null;
                        continue;
                    }
                    terminalId = property.Value.GetString();
                    continue;
                }
            }
            return new TerminalAssignment(tenantId, timeStamp, terminalId.Value);
        }
    }
}
