// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The TerminalAssignment. </summary>
    public partial class TerminalAssignment
    {
        /// <summary> Initializes a new instance of TerminalAssignment. </summary>
        /// <param name="tenantId"></param>
        /// <param name="timeStamp"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="tenantId"/> is null. </exception>
        internal TerminalAssignment(string tenantId, DateTimeOffset timeStamp)
        {
            Argument.AssertNotNull(tenantId, nameof(tenantId));

            TenantId = tenantId;
            TimeStamp = timeStamp;
        }

        /// <summary> Initializes a new instance of TerminalAssignment. </summary>
        /// <param name="terminalId"></param>
        /// <param name="tenantId"></param>
        /// <param name="timeStamp"></param>
        internal TerminalAssignment(string terminalId, string tenantId, DateTimeOffset timeStamp)
        {
            TerminalId = terminalId;
            TenantId = tenantId;
            TimeStamp = timeStamp;
        }

        /// <summary> Gets the terminal id. </summary>
        public string TerminalId { get; }
        /// <summary> Gets the tenant id. </summary>
        public string TenantId { get; }
        /// <summary> Gets the time stamp. </summary>
        public DateTimeOffset TimeStamp { get; }
    }
}
