// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The TerminalStatus. </summary>
    public readonly partial struct TerminalStatus : IEquatable<TerminalStatus>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="TerminalStatus"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public TerminalStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string NoneValue = "none";
        private const string ActiveValue = "active";
        private const string ReportedValue = "reported";
        private const string BlockedValue = "blocked";

        /// <summary> none. </summary>
        public static TerminalStatus None { get; } = new TerminalStatus(NoneValue);
        /// <summary> active. </summary>
        public static TerminalStatus Active { get; } = new TerminalStatus(ActiveValue);
        /// <summary> reported. </summary>
        public static TerminalStatus Reported { get; } = new TerminalStatus(ReportedValue);
        /// <summary> blocked. </summary>
        public static TerminalStatus Blocked { get; } = new TerminalStatus(BlockedValue);
        /// <summary> Determines if two <see cref="TerminalStatus"/> values are the same. </summary>
        public static bool operator ==(TerminalStatus left, TerminalStatus right) => left.Equals(right);
        /// <summary> Determines if two <see cref="TerminalStatus"/> values are not the same. </summary>
        public static bool operator !=(TerminalStatus left, TerminalStatus right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="TerminalStatus"/>. </summary>
        public static implicit operator TerminalStatus(string value) => new TerminalStatus(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is TerminalStatus other && Equals(other);
        /// <inheritdoc />
        public bool Equals(TerminalStatus other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
