// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Deveel.Messaging.Terminals.Management.Models
{
    /// <summary> The ValidationProblemDetails. </summary>
    internal partial class ValidationProblemDetails
    {
        /// <summary> Initializes a new instance of ValidationProblemDetails. </summary>
        internal ValidationProblemDetails()
        {
            Errors = new ChangeTrackingDictionary<string, IList<string>>();
            AdditionalProperties = new ChangeTrackingDictionary<string, object>();
        }

        /// <summary> Initializes a new instance of ValidationProblemDetails. </summary>
        /// <param name="type"></param>
        /// <param name="title"></param>
        /// <param name="status"></param>
        /// <param name="detail"></param>
        /// <param name="instance"></param>
        /// <param name="errors"> Dictionary of &lt;components·1ctgts0·schemas·validationproblemdetails·properties·errors·additionalproperties&gt;. </param>
        /// <param name="additionalProperties"> Additional Properties. </param>
        internal ValidationProblemDetails(string type, string title, int? status, string detail, string instance, IReadOnlyDictionary<string, IList<string>> errors, IReadOnlyDictionary<string, object> additionalProperties)
        {
            Type = type;
            Title = title;
            Status = status;
            Detail = detail;
            Instance = instance;
            Errors = errors;
            AdditionalProperties = additionalProperties;
        }

        /// <summary> Gets the type. </summary>
        public string Type { get; }
        /// <summary> Gets the title. </summary>
        public string Title { get; }
        /// <summary> Gets the status. </summary>
        public int? Status { get; }
        /// <summary> Gets the detail. </summary>
        public string Detail { get; }
        /// <summary> Gets the instance. </summary>
        public string Instance { get; }
        /// <summary> Dictionary of &lt;components·1ctgts0·schemas·validationproblemdetails·properties·errors·additionalproperties&gt;. </summary>
        public IReadOnlyDictionary<string, IList<string>> Errors { get; }
        /// <summary> Additional Properties. </summary>
        public IReadOnlyDictionary<string, object> AdditionalProperties { get; }
    }
}
