// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The specification of an API Key used to secure a channel
    /// </summary>
    public partial class ApiKeyCredentials
    {
        /// <summary>
        /// Initializes a new instance of the ApiKeyCredentials class.
        /// </summary>
        public ApiKeyCredentials()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiKeyCredentials class.
        /// </summary>
        /// <param name="value">The value of the key</param>
        public ApiKeyCredentials(string value)
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the value of the key
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Value == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Value");
            }
        }
    }
}
