// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for ChannelSource.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(ChannelSourceConverter))]
    public struct ChannelSource : System.IEquatable<ChannelSource>
    {
        private ChannelSource(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly ChannelSource Unknown = "unknown";

        public static readonly ChannelSource Inventory = "inventory";

        public static readonly ChannelSource Customer = "customer";


        /// <summary>
        /// Underlying value of enum ChannelSource
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for ChannelSource
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type ChannelSource
        /// </summary>
        public bool Equals(ChannelSource e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to ChannelSource
        /// </summary>
        public static implicit operator ChannelSource(string value)
        {
            return new ChannelSource(value);
        }

        /// <summary>
        /// Implicit operator to convert ChannelSource to string
        /// </summary>
        public static implicit operator string(ChannelSource e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum ChannelSource
        /// </summary>
        public static bool operator == (ChannelSource e1, ChannelSource e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum ChannelSource
        /// </summary>
        public static bool operator != (ChannelSource e1, ChannelSource e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for ChannelSource
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is ChannelSource && Equals((ChannelSource)obj);
        }

        /// <summary>
        /// Returns for hashCode ChannelSource
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
