// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The response to the request of assignment of a channel
    /// </summary>
    public partial class ChannelAssignmentResponse
    {
        /// <summary>
        /// Initializes a new instance of the ChannelAssignmentResponse class.
        /// </summary>
        public ChannelAssignmentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChannelAssignmentResponse class.
        /// </summary>
        /// <param name="responder">The unique identifier of the user
        /// responding</param>
        /// <param name="responseType">Possible values include: 'none',
        /// 'accepted', 'rejected'</param>
        /// <param name="timeStamp">The exact time-stamp of the
        /// response</param>
        /// <param name="notes">An optional set of notes that inform on the
        /// motivation and reasons of the response</param>
        public ChannelAssignmentResponse(string responder, ResourceAssignmentResponseType responseType, System.DateTimeOffset timeStamp, string notes = default(string))
        {
            Responder = responder;
            ResponseType = responseType;
            TimeStamp = timeStamp;
            Notes = notes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique identifier of the user responding
        /// </summary>
        [JsonProperty(PropertyName = "responder")]
        public string Responder { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'none', 'accepted',
        /// 'rejected'
        /// </summary>
        [JsonProperty(PropertyName = "responseType")]
        public ResourceAssignmentResponseType ResponseType { get; set; }

        /// <summary>
        /// Gets or sets the exact time-stamp of the response
        /// </summary>
        [JsonProperty(PropertyName = "timeStamp")]
        public System.DateTimeOffset TimeStamp { get; set; }

        /// <summary>
        /// Gets or sets an optional set of notes that inform on the
        /// motivation and reasons of the response
        /// </summary>
        [JsonProperty(PropertyName = "notes")]
        public string Notes { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Responder == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Responder");
            }
        }
    }
}
