// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The request of assignment of a channel from the inventory
    /// </summary>
    public partial class ChannelAssignmentRequest
    {
        /// <summary>
        /// Initializes a new instance of the ChannelAssignmentRequest class.
        /// </summary>
        public ChannelAssignmentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChannelAssignmentRequest class.
        /// </summary>
        /// <param name="requester">The identifier of the user that made the
        /// request</param>
        /// <param name="timeStamp">The exact time-stamp of the request</param>
        /// <param name="id">The unique identifier of the request</param>
        public ChannelAssignmentRequest(RequestedChannel channel, string requester, System.DateTimeOffset timeStamp, string id, ChannelAssignmentResponse response = default(ChannelAssignmentResponse), ChannelAssignment assignment = default(ChannelAssignment))
        {
            Channel = channel;
            Response = response;
            Requester = requester;
            TimeStamp = timeStamp;
            Id = id;
            Assignment = assignment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channel")]
        public RequestedChannel Channel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "response")]
        public ChannelAssignmentResponse Response { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user that made the request
        /// </summary>
        [JsonProperty(PropertyName = "requester")]
        public string Requester { get; set; }

        /// <summary>
        /// Gets or sets the exact time-stamp of the request
        /// </summary>
        [JsonProperty(PropertyName = "timeStamp")]
        public System.DateTimeOffset TimeStamp { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the request
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assignment")]
        public ChannelAssignment Assignment { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Channel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Channel");
            }
            if (Requester == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Requester");
            }
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Channel != null)
            {
                Channel.Validate();
            }
            if (Response != null)
            {
                Response.Validate();
            }
            if (Assignment != null)
            {
                Assignment.Validate();
            }
        }
    }
}
