// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for ChannelDirections.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(ChannelDirectionsConverter))]
    public struct ChannelDirections : System.IEquatable<ChannelDirections>
    {
        private ChannelDirections(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly ChannelDirections Default = "default";

        public static readonly ChannelDirections Out = "out";

        public static readonly ChannelDirections In = "in";

        public static readonly ChannelDirections Duplex = "duplex";


        /// <summary>
        /// Underlying value of enum ChannelDirections
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for ChannelDirections
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type ChannelDirections
        /// </summary>
        public bool Equals(ChannelDirections e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to ChannelDirections
        /// </summary>
        public static implicit operator ChannelDirections(string value)
        {
            return new ChannelDirections(value);
        }

        /// <summary>
        /// Implicit operator to convert ChannelDirections to string
        /// </summary>
        public static implicit operator string(ChannelDirections e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum ChannelDirections
        /// </summary>
        public static bool operator == (ChannelDirections e1, ChannelDirections e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum ChannelDirections
        /// </summary>
        public static bool operator != (ChannelDirections e1, ChannelDirections e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for ChannelDirections
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is ChannelDirections && Equals((ChannelDirections)obj);
        }

        /// <summary>
        /// Returns for hashCode ChannelDirections
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
