// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Specifies the rules to route inbound messages (delivered as webhooks)
    /// </summary>
    public partial class MessageRoute
    {
        /// <summary>
        /// Initializes a new instance of the MessageRoute class.
        /// </summary>
        public MessageRoute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageRoute class.
        /// </summary>
        /// <param name="id">The unique identifier of the route</param>
        /// <param name="name">The descriptive name of the route</param>
        /// <param name="active">Indicates the active state of a route</param>
        /// <param name="destinationUrl">The HTTP URL address where the inbound
        /// message
        /// will be delivered</param>
        /// <param name="retryCount">The number of retries to deliver the
        /// inbound message</param>
        /// <param name="secret">A secret code that is used to sign the
        /// webhooks</param>
        /// <param name="context">A context that is appended to the message
        /// before
        /// the delivery (useful for correlation)</param>
        /// <param name="match">A list of rules that are used to match a
        /// message to the given route</param>
        public MessageRoute(RouteChannel channel, string id, string name, bool active, string destinationUrl, int? retryCount = default(int?), string secret = default(string), IDictionary<string, object> context = default(IDictionary<string, object>), IList<RouteMatchRule> match = default(IList<RouteMatchRule>))
        {
            Channel = channel;
            Id = id;
            Name = name;
            Active = active;
            DestinationUrl = destinationUrl;
            RetryCount = retryCount;
            Secret = secret;
            Context = context;
            Match = match;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channel")]
        public RouteChannel Channel { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the route
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the descriptive name of the route
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets indicates the active state of a route
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool Active { get; set; }

        /// <summary>
        /// Gets or sets the HTTP URL address where the inbound message
        /// will be delivered
        /// </summary>
        [JsonProperty(PropertyName = "destinationUrl")]
        public string DestinationUrl { get; set; }

        /// <summary>
        /// Gets or sets the number of retries to deliver the inbound message
        /// </summary>
        [JsonProperty(PropertyName = "retryCount")]
        public int? RetryCount { get; set; }

        /// <summary>
        /// Gets or sets a secret code that is used to sign the webhooks
        /// </summary>
        [JsonProperty(PropertyName = "secret")]
        public string Secret { get; set; }

        /// <summary>
        /// Gets or sets a context that is appended to the message before
        /// the delivery (useful for correlation)
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public IDictionary<string, object> Context { get; set; }

        /// <summary>
        /// Gets or sets a list of rules that are used to match a message to
        /// the given route
        /// </summary>
        [JsonProperty(PropertyName = "match")]
        public IList<RouteMatchRule> Match { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Channel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Channel");
            }
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (DestinationUrl == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DestinationUrl");
            }
            if (Channel != null)
            {
                Channel.Validate();
            }
            if (Match != null)
            {
                foreach (var element in Match)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
