// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for MessageContentType.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(MessageContentTypeConverter))]
    public struct MessageContentType : System.IEquatable<MessageContentType>
    {
        private MessageContentType(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly MessageContentType Text = "text";

        public static readonly MessageContentType Html = "html";

        public static readonly MessageContentType Multipart = "multipart";

        public static readonly MessageContentType Card = "card";

        public static readonly MessageContentType Template = "template";

        public static readonly MessageContentType Media = "media";


        /// <summary>
        /// Underlying value of enum MessageContentType
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for MessageContentType
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type MessageContentType
        /// </summary>
        public bool Equals(MessageContentType e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to MessageContentType
        /// </summary>
        public static implicit operator MessageContentType(string value)
        {
            return new MessageContentType(value);
        }

        /// <summary>
        /// Implicit operator to convert MessageContentType to string
        /// </summary>
        public static implicit operator string(MessageContentType e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum MessageContentType
        /// </summary>
        public static bool operator == (MessageContentType e1, MessageContentType e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum MessageContentType
        /// </summary>
        public static bool operator != (MessageContentType e1, MessageContentType e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for MessageContentType
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is MessageContentType && Equals((MessageContentType)obj);
        }

        /// <summary>
        /// Returns for hashCode MessageContentType
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
