// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for PageSortDirection.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(PageSortDirectionConverter))]
    public struct PageSortDirection : System.IEquatable<PageSortDirection>
    {
        private PageSortDirection(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly PageSortDirection Default = "default";

        public static readonly PageSortDirection Asc = "asc";

        public static readonly PageSortDirection Desc = "desc";


        /// <summary>
        /// Underlying value of enum PageSortDirection
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for PageSortDirection
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type PageSortDirection
        /// </summary>
        public bool Equals(PageSortDirection e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to PageSortDirection
        /// </summary>
        public static implicit operator PageSortDirection(string value)
        {
            return new PageSortDirection(value);
        }

        /// <summary>
        /// Implicit operator to convert PageSortDirection to string
        /// </summary>
        public static implicit operator string(PageSortDirection e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum PageSortDirection
        /// </summary>
        public static bool operator == (PageSortDirection e1, PageSortDirection e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum PageSortDirection
        /// </summary>
        public static bool operator != (PageSortDirection e1, PageSortDirection e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for PageSortDirection
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is PageSortDirection && Equals((PageSortDirection)obj);
        }

        /// <summary>
        /// Returns for hashCode PageSortDirection
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
