// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RangeFilter
    {
        /// <summary>
        /// Initializes a new instance of the RangeFilter class.
        /// </summary>
        public RangeFilter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RangeFilter class.
        /// </summary>
        public RangeFilter(string field, FilterValue lower = default(FilterValue), FilterValue upper = default(FilterValue))
        {
            Field = field;
            Lower = lower;
            Upper = upper;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lower")]
        public FilterValue Lower { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upper")]
        public FilterValue Upper { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Field == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Field");
            }
            if (Lower != null)
            {
                Lower.Validate();
            }
            if (Upper != null)
            {
                Upper.Validate();
            }
        }
    }
}
