// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RequestedTerminal
    {
        /// <summary>
        /// Initializes a new instance of the RequestedTerminal class.
        /// </summary>
        public RequestedTerminal()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RequestedTerminal class.
        /// </summary>
        /// <param name="type">Possible values include: 'email', 'phoneNumber',
        /// 'alphaNumeric'</param>
        public RequestedTerminal(string terminalId, ServerTerminalType? type = default(ServerTerminalType?), string address = default(string))
        {
            TerminalId = terminalId;
            Type = type;
            Address = address;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "terminalId")]
        public string TerminalId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'email', 'phoneNumber',
        /// 'alphaNumeric'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public ServerTerminalType? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (TerminalId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TerminalId");
            }
        }
    }
}
