// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for ResourceAssignmentResponseType.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(ResourceAssignmentResponseTypeConverter))]
    public struct ResourceAssignmentResponseType : System.IEquatable<ResourceAssignmentResponseType>
    {
        private ResourceAssignmentResponseType(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly ResourceAssignmentResponseType None = "none";

        public static readonly ResourceAssignmentResponseType Accepted = "accepted";

        public static readonly ResourceAssignmentResponseType Rejected = "rejected";


        /// <summary>
        /// Underlying value of enum ResourceAssignmentResponseType
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for ResourceAssignmentResponseType
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type ResourceAssignmentResponseType
        /// </summary>
        public bool Equals(ResourceAssignmentResponseType e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to
        /// ResourceAssignmentResponseType
        /// </summary>
        public static implicit operator ResourceAssignmentResponseType(string value)
        {
            return new ResourceAssignmentResponseType(value);
        }

        /// <summary>
        /// Implicit operator to convert ResourceAssignmentResponseType to
        /// string
        /// </summary>
        public static implicit operator string(ResourceAssignmentResponseType e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum ResourceAssignmentResponseType
        /// </summary>
        public static bool operator == (ResourceAssignmentResponseType e1, ResourceAssignmentResponseType e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum ResourceAssignmentResponseType
        /// </summary>
        public static bool operator != (ResourceAssignmentResponseType e1, ResourceAssignmentResponseType e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for ResourceAssignmentResponseType
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is ResourceAssignmentResponseType && Equals((ResourceAssignmentResponseType)obj);
        }

        /// <summary>
        /// Returns for hashCode ResourceAssignmentResponseType
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
