// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ServerTerminal
    {
        /// <summary>
        /// Initializes a new instance of the ServerTerminal class.
        /// </summary>
        public ServerTerminal()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServerTerminal class.
        /// </summary>
        /// <param name="type">Possible values include: 'email', 'phoneNumber',
        /// 'alphaNumeric'</param>
        /// <param name="status">Possible values include: 'none', 'active',
        /// 'reported', 'blocked'</param>
        /// <param name="source">Possible values include: 'unknown',
        /// 'inventory', 'customer'</param>
        /// <param name="role">Possible values include: 'default', 'sender',
        /// 'receiver', 'both'</param>
        public ServerTerminal(ServerTerminalType type, string address, TerminalStatus status, TerminalSource source, TerminalRoles role, string provider, System.DateTimeOffset? lastChanged = default(System.DateTimeOffset?), string sourceId = default(string), IDictionary<string, object> settings = default(IDictionary<string, object>), string id = default(string))
        {
            Type = type;
            Address = address;
            Status = status;
            LastChanged = lastChanged;
            Source = source;
            Role = role;
            SourceId = sourceId;
            Settings = settings;
            Provider = provider;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'email', 'phoneNumber',
        /// 'alphaNumeric'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public ServerTerminalType Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'none', 'active', 'reported',
        /// 'blocked'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public TerminalStatus Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastChanged")]
        public System.DateTimeOffset? LastChanged { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'unknown', 'inventory',
        /// 'customer'
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public TerminalSource Source { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'default', 'sender',
        /// 'receiver', 'both'
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public TerminalRoles Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceId")]
        public string SourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settings")]
        public IDictionary<string, object> Settings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provider")]
        public string Provider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Address == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Address");
            }
            if (Provider == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Provider");
            }
        }
    }
}
