// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for ServerTerminalType.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(ServerTerminalTypeConverter))]
    public struct ServerTerminalType : System.IEquatable<ServerTerminalType>
    {
        private ServerTerminalType(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly ServerTerminalType Email = "email";

        public static readonly ServerTerminalType PhoneNumber = "phoneNumber";

        public static readonly ServerTerminalType AlphaNumeric = "alphaNumeric";


        /// <summary>
        /// Underlying value of enum ServerTerminalType
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for ServerTerminalType
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type ServerTerminalType
        /// </summary>
        public bool Equals(ServerTerminalType e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to ServerTerminalType
        /// </summary>
        public static implicit operator ServerTerminalType(string value)
        {
            return new ServerTerminalType(value);
        }

        /// <summary>
        /// Implicit operator to convert ServerTerminalType to string
        /// </summary>
        public static implicit operator string(ServerTerminalType e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum ServerTerminalType
        /// </summary>
        public static bool operator == (ServerTerminalType e1, ServerTerminalType e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum ServerTerminalType
        /// </summary>
        public static bool operator != (ServerTerminalType e1, ServerTerminalType e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for ServerTerminalType
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is ServerTerminalType && Equals((ServerTerminalType)obj);
        }

        /// <summary>
        /// Returns for hashCode ServerTerminalType
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
