// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubjectGrant
    {
        /// <summary>
        /// Initializes a new instance of the SubjectGrant class.
        /// </summary>
        public SubjectGrant()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubjectGrant class.
        /// </summary>
        public SubjectGrant(string grantedBy = default(string), IList<Permission> permissions = default(IList<Permission>), System.DateTimeOffset? grantedAt = default(System.DateTimeOffset?), string id = default(string))
        {
            GrantedBy = grantedBy;
            Permissions = permissions;
            GrantedAt = grantedAt;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grantedBy")]
        public string GrantedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permissions")]
        public IList<Permission> Permissions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grantedAt")]
        public System.DateTimeOffset? GrantedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

    }
}
