// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for TerminalStatus.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(TerminalStatusConverter))]
    public struct TerminalStatus : System.IEquatable<TerminalStatus>
    {
        private TerminalStatus(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly TerminalStatus None = "none";

        public static readonly TerminalStatus Active = "active";

        public static readonly TerminalStatus Reported = "reported";

        public static readonly TerminalStatus Blocked = "blocked";


        /// <summary>
        /// Underlying value of enum TerminalStatus
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for TerminalStatus
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type TerminalStatus
        /// </summary>
        public bool Equals(TerminalStatus e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to TerminalStatus
        /// </summary>
        public static implicit operator TerminalStatus(string value)
        {
            return new TerminalStatus(value);
        }

        /// <summary>
        /// Implicit operator to convert TerminalStatus to string
        /// </summary>
        public static implicit operator string(TerminalStatus e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum TerminalStatus
        /// </summary>
        public static bool operator == (TerminalStatus e1, TerminalStatus e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum TerminalStatus
        /// </summary>
        public static bool operator != (TerminalStatus e1, TerminalStatus e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for TerminalStatus
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is TerminalStatus && Equals((TerminalStatus)obj);
        }

        /// <summary>
        /// Returns for hashCode TerminalStatus
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
