// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for TerminalRoles.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(TerminalRolesConverter))]
    public struct TerminalRoles : System.IEquatable<TerminalRoles>
    {
        private TerminalRoles(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly TerminalRoles Default = "default";

        public static readonly TerminalRoles Sender = "sender";

        public static readonly TerminalRoles Receiver = "receiver";

        public static readonly TerminalRoles Both = "both";


        /// <summary>
        /// Underlying value of enum TerminalRoles
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for TerminalRoles
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type TerminalRoles
        /// </summary>
        public bool Equals(TerminalRoles e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to TerminalRoles
        /// </summary>
        public static implicit operator TerminalRoles(string value)
        {
            return new TerminalRoles(value);
        }

        /// <summary>
        /// Implicit operator to convert TerminalRoles to string
        /// </summary>
        public static implicit operator string(TerminalRoles e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum TerminalRoles
        /// </summary>
        public static bool operator == (TerminalRoles e1, TerminalRoles e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum TerminalRoles
        /// </summary>
        public static bool operator != (TerminalRoles e1, TerminalRoles e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for TerminalRoles
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is TerminalRoles && Equals((TerminalRoles)obj);
        }

        /// <summary>
        /// Returns for hashCode TerminalRoles
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
