// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for UserIdentityType.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(UserIdentityTypeConverter))]
    public struct UserIdentityType : System.IEquatable<UserIdentityType>
    {
        private UserIdentityType(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly UserIdentityType Unknown = "unknown";

        public static readonly UserIdentityType Managed = "managed";

        public static readonly UserIdentityType Social = "social";


        /// <summary>
        /// Underlying value of enum UserIdentityType
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for UserIdentityType
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type UserIdentityType
        /// </summary>
        public bool Equals(UserIdentityType e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to UserIdentityType
        /// </summary>
        public static implicit operator UserIdentityType(string value)
        {
            return new UserIdentityType(value);
        }

        /// <summary>
        /// Implicit operator to convert UserIdentityType to string
        /// </summary>
        public static implicit operator string(UserIdentityType e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum UserIdentityType
        /// </summary>
        public static bool operator == (UserIdentityType e1, UserIdentityType e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum UserIdentityType
        /// </summary>
        public static bool operator != (UserIdentityType e1, UserIdentityType e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for UserIdentityType
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is UserIdentityType && Equals((UserIdentityType)obj);
        }

        /// <summary>
        /// Returns for hashCode UserIdentityType
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
