// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for WebFilterOperator.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(WebFilterOperatorConverter))]
    public struct WebFilterOperator : System.IEquatable<WebFilterOperator>
    {
        private WebFilterOperator(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly WebFilterOperator Eq = "eq";

        public static readonly WebFilterOperator Ne = "ne";

        public static readonly WebFilterOperator Gt = "gt";

        public static readonly WebFilterOperator Gte = "gte";

        public static readonly WebFilterOperator Lt = "lt";

        public static readonly WebFilterOperator Lte = "lte";

        public static readonly WebFilterOperator Between = "between";

        public static readonly WebFilterOperator Contains = "contains";

        public static readonly WebFilterOperator StartsWith = "startsWith";

        public static readonly WebFilterOperator EndsWith = "endsWith";


        /// <summary>
        /// Underlying value of enum WebFilterOperator
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for WebFilterOperator
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type WebFilterOperator
        /// </summary>
        public bool Equals(WebFilterOperator e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to WebFilterOperator
        /// </summary>
        public static implicit operator WebFilterOperator(string value)
        {
            return new WebFilterOperator(value);
        }

        /// <summary>
        /// Implicit operator to convert WebFilterOperator to string
        /// </summary>
        public static implicit operator string(WebFilterOperator e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum WebFilterOperator
        /// </summary>
        public static bool operator == (WebFilterOperator e1, WebFilterOperator e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum WebFilterOperator
        /// </summary>
        public static bool operator != (WebFilterOperator e1, WebFilterOperator e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for WebFilterOperator
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is WebFilterOperator && Equals((WebFilterOperator)obj);
        }

        /// <summary>
        /// Returns for hashCode WebFilterOperator
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
