// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Management.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A request to change the active status of a subscription
    /// </summary>
    public partial class WebhookSubscriptionStatusUpdate
    {
        /// <summary>
        /// Initializes a new instance of the WebhookSubscriptionStatusUpdate
        /// class.
        /// </summary>
        public WebhookSubscriptionStatusUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebhookSubscriptionStatusUpdate
        /// class.
        /// </summary>
        /// <param name="active">Wether or not the subscription should be
        /// active</param>
        public WebhookSubscriptionStatusUpdate(bool active)
        {
            Active = active;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets wether or not the subscription should be active
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool Active { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
