// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Messaging.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A terminal used to send messages to receivers (typically from a server
    /// application)
    /// </summary>
    public partial class SenderTerminal
    {
        /// <summary>
        /// Initializes a new instance of the SenderTerminal class.
        /// </summary>
        public SenderTerminal()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SenderTerminal class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="label">The sender is an alpha-numeric label</param>
        /// <param name="id">The identifier of a terminal provisioned to the
        /// tenant</param>
        public SenderTerminal(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string label = default(string), string id = default(string), string emailAddress = default(string), EmailAddress email = default(EmailAddress), string number = default(string), string conversation = default(string), string user = default(string), string url = default(string))
        {
            AdditionalProperties = additionalProperties;
            Label = label;
            Id = id;
            EmailAddress = emailAddress;
            Email = email;
            Number = number;
            Conversation = conversation;
            User = user;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets the sender is an alpha-numeric label
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or sets the identifier of a terminal provisioned to the tenant
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public EmailAddress Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conversation")]
        public string Conversation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public string User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Email != null)
            {
                Email.Validate();
            }
        }
    }
}
