name: SDK CI Build

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    needs:
      - dotnet-channel

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET ${{matrix.dotnet}}
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: 6.0.x

      - name: Restore the .NET Dependencies
        run: dotnet restore ./dotnet

      - name: Build the .NET SDK
        run: dotnet build ./dotnet/Deveel.Ocm.Sdk.sln -c Release --no-restore

      - name: Test
        run: dotnet test ./test/**/*.csproj --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*.XUnit]*" /p:Exclude="[*.Client]*"

      - name: Pack Common Libraries
        run: dotnet pack ./dotnet/Deveel.Ocm.Sdk.sln -c Release --no-restore --no-build --include-symbols --version-suffix $GITHUB_RUN_ID --output ./nuget

      - name: Push Packages to GitHub NuGet
        run: dotnet nuget push ./nuget/**/*.nupkg --skip-duplicate --api-key ${{secrets.DEVEEL_NUGET_TOKEN}} --source "Deveel GitHub"

  dotnet-channel:
    runs-on: ubuntu-latest

    steps:
      - uses: deveel/deveel.ocm.sdk/.github/workflows/dotnet-channel.yml@main
      - uses: actions/download-artifact@v3
        with:
          name: channels-client
          path: ./dotnet/src/Deveel.Ocm.Channels.Management/Management
