name: SDK CI Build

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    needs:
      - dotnet-terminal-client
      - dotnet-route-client
      - dotnet-channel-client

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: 7.0.x

      - name: Copying the generated Terminals Client
        uses: actions/download-artifact@v3
        with:
          name: terminal-client
          path: ./dotnet/src/Deveel.Ocm.Terminal.Client/Terminals/Management

      - name: Copying the generated Routes Client
        uses: actions/download-artifact@v3
        with:
          name: route-client
          path: ./dotnet/src/Deveel.Ocm.Route.Client/Routes/Management

      - name: Add Deveel GitHub NuGet Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/deveel/index.json" -n "Deveel GitHub" -u ${{secrets.DEVEEL_NUGET_USER}} -p ${{ secrets.DEVEEL_NUGET_TOKEN }} --store-password-in-clear-text

      - name: Restore the dependencies
        run: dotnet restore ./dotnet/Deveel.Ocm.Sdk.sln

      - name: Build the .NET SDK
        run: dotnet build "./dotnet/Deveel.Ocm.Sdk.sln" -c Release --version-suffix $GITHUB_RUN_ID --no-restore

      # - name: Test
      #   run: dotnet test ./test/**/*.csproj --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*.XUnit]*" /p:Exclude="[*.Client]*"

      - name: Pack Common Libraries
        run: dotnet pack "./dotnet/Deveel.Ocm.Sdk.sln" -c Release --no-restore --no-build --include-symbols --version-suffix $GITHUB_RUN_ID --output ./nuget

      - name: Push Packages to GitHub NuGet
        run: dotnet nuget push ./nuget/**/*.nupkg --skip-duplicate --api-key ${{secrets.DEVEEL_NUGET_TOKEN}} --source "Deveel GitHub"

  dotnet-terminal-client:
    uses: ./.github/workflows/dotnet-client.yml
    with:
      serviceName: terminal
      plane: management
      version: v1
      namespace: Deveel.Messaging.Terminals.Management
      clientName: TerminalClient

  dotnet-route-client:
    uses: ./.github/workflows/dotnet-client.yml
    with:
      serviceName: route
      plane: management
      version: v1
      namespace: Deveel.Messaging.Routes.Management
      clientName: RouteClient

  dotnet-channel-client:
     uses: ./.github/workflows/dotnet-client.yml
     with:
       serviceName: channel
       plane: management
       version: v1
       namespace: Deveel.Messaging.Channels.Management
       clientName: ChannelClient