name: ".NET Client CI/CD"

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: "The environment of the client"
        required: false
        default: dev
      artifactName:
        type: string
        description: "The name of the artifact to restore"
        required: true
      clientType:
        type: string
        description: "The type of client to generate and deploy"
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: "Generate the .NET Management Client"
      if: ${{inputs.clientType}} == 'management'
      run: |
        autorest --input-file=./openapi/${{inputs.artifactName}} `
        --output-folder=./dotnet/src/Deveel.Ocm.Management.Client/Messaging/Management `
        --project-folder=./dotnet/src/Deveel.Ocm.Management.Client `
        --namespace=Deveel.Messaging.Management `
        --csharp `
        --add-credentials `
        --sync-methods=all `
        --override-client-name=ManagementClient `
        --use-datetimeoffset `
        --head-as-boolean `
        --public-clients `
        --version=3.0.6349 `
        --v3
    - name: "Generate the .NET Messaging Client"
      if: ${{inputs.clientType}} == 'messaging'
      run: |
        autorest --input-file=./openapi/${{inputs.artifactName}} `
        --output-folder=./dotnet/src/Deveel.Ocm.Client/Messaging `
        --project-folder=./dotnet/src/Deveel.Ocm.Client `
        --namespace=Deveel.Messaging `
        --csharp `
        --add-credentials `
        --sync-methods=all `
        --override-client-name=MessagingClient `
        --use-datetimeoffset `
        --head-as-boolean `
        --public-clients `
        --version=3.0.6349 `
        --v3