name: ".NET Client Generation"

on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        description: "The name of the service that the client addresses"
        required: true
      plane:
        type: string
        description: "The plane where the client exists (data or management)"
        required: true
      commitId:
        type: string
        description: "The reference to the commit to build"
        required: false
        default: main
      version:
        type: string
        required: true
        description: The version number of the specification
      namespace:
        type: string
        required: true
        description: The namespace of the generated client code
      clientName:
         type: string
         required: false
         description: "The name of client class (if applicable)"
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: npm install -g autorest

    - name: "Generate the .NET Client"
      run: |
        autorest --input-file=https://raw.githubusercontent.com/deveel/deveel.ocm.specs/${{inputs.commitId}}/specs/${{inputs.serviceName}}/${{inputs.plane}}/${{inputs.version}}/${{inputs.serviceName}}-${{inputs.version}}.json \
        --output-folder=.\client \
        --namespace=${{inputs.namespace}} \
        --csharp \
        --add-credentials \
        --override-client-name=${{inputs.clientName}} \
	    --public-clients \
	    --skip-csproj \
	    --clear-output-folder \
	    --generation1-convenience-client \
	    --v3

    - uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.serviceName}}-client
        path: ./client/
