name: Channel Clients CD

on:
  push:
    branches: [main]

  workflow_call:

jobs:
  build:
    # if: startsWith(github.event.head_commit.message, '#channel v1 dev')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install AutoRest
        run: npm install -g autorest

      - name: "Generate the .NET Channel Management Client"
        run: |
          autorest --input-file=./specs/v1/dev/mgmt-v1/channel/ocm-channel-api-v1.json \
                   --output-folder=./client \
                   --namespace=Deveel.Messaging.Channels.Management \
                   --csharp \
                   --add-credentials \
                   --override-client-name=ChannelClient \
                   --public-clients \
                   --skip-csproj \
                   --clear-output-folder \
                   --generation1-convenience-client \
                   --v3

      - uses: actions/upload-artifact@v3
        with:
          name: channels-client
          path: ./client/

      # - name: Add Deveel GitHub NuGet Source
      #   run: dotnet nuget add source "https://nuget.pkg.github.com/deveel/index.json" -n "Deveel GitHub" -u ${{secrets.DEVEEL_NUGET_USER}} -p ${{ secrets.DEVEEL_NUGET_TOKEN }} --store-password-in-clear-text

      # - name: Build .NET Channel Clients
      #   run: dotnet build ./dotnet/src/Deveel.Ocm.Channels.Management/Deveels.Ocm.Channel.Management.csproj -c Release

      # - name: Pack Clients
      #   run: dotnet pack "./dotnet/src/Deveel.Ocm.Channel.Management/Deveel.Ocm.Channel.Management.csproj" -c Release --no-restore --no-build --include-symbols --version-suffix $GITHUB_RUN_ID --output ./nuget

      # - name: Push Packages to GitHub NuGet
      #   run: dotnet nuget push "**/*.nupkg" --skip-duplicate --api-key ${{secrets.GITHUB_TOKEN}} --source "Deveel GitHub"
