name: SDK PR Build

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    needs: 
    - dotnet-mgmt-client
    - dotnet-msg-client

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: [6.0.x]
        
    runs-on: ${{matrix.os}}

    steps:
    
      - name: Setup .NET ${{matrix.dotnet}}
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: ${{matrix.dotnet}}

      - name: Restore the .NET Dependencies
        run: dotnet restore Deveel.Ocm.Sdk.sln
      
      - name: Build the .NET SDK
        run: dotnet build ./dotnet/Deveel.Ocm.Sdk.sln -c Release --no-restore
        
      - name: Test
        run: dotnet test ./test/**/*.csproj --no-build --verbosity normal -c Release

  dotnet-mgmt-client:
    uses: deveel/deveel.ocm.sdk/.github/workflows/dotnet-client.yml@main
    with:
      artifactName: ocm-mgmt-api-v1.json
      clientType: management
      commitId: $GITHUB_SHA

  dotnet-msg-client:
    uses: deveel/deveel.ocm.sdk/.github/workflows/dotnet-client.yml@main
    with:
      artifactName: ocm-api-v1.json
      clientType: messaging
      commitId: $GITHUB_SHA